
server:
  port: 80

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/zero_1_demo
    password: Sobirov0717
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

